# Generated by Django 4.0.3 on 2022-04-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('target_amount', models.IntegerField()),
                ('end_date', models.DateField()),
                ('amount_per_time', models.IntegerField()),
            ],
        ),
    ]
